import * as THREE from 'three';
import { gsap } from 'gsap';

export const CHAPTERS = [
  {
    morph: 0,
    cubeOpacity: 1,
    headOpacity: 0,
    modelScale: 0.55,
    warp: 0.045,
    headWarp: 0,
    chaos: 0.08,
    shake: 0,
    rotationRate: 0.2,
    spinMix: 1,
    colorPhase: 0,
    hueCycleRate: 0,
    glitchStrength: 0,
    glitchRate: 0,
    sludge: 0.2,
    fieldForm: 0,
    fieldOpacity: 0.38,
    fieldMotion: 0.1,
    cameraZ: 7,
    cameraFov: 38,
    cameraDrift: 0.02,
    baseRotX: -0.18,
    baseRotY: -0.38,
    baseRotZ: 0.04,
    idlePitch: 0.007,
    idleYaw: 0.02,
    idleRoll: 0.004,
    keyX: -0.45,
    keyY: 0.8,
    keyZ: 0.75,
    keyIntensity: 0.96,
    fillIntensity: 0.16,
    rimIntensity: 0.38,
    lightSweep: 0.05,
    specular: 0.24,
    glowOpacity: 0.46,
    glowScale: 1.03,
    grainOpacity: 0.15,
    hue: '0deg',
  },
  {
    morph: 0.015,
    cubeOpacity: 1,
    headOpacity: 0,
    modelScale: 1,
    warp: 0.22,
    headWarp: 0,
    chaos: 0.34,
    shake: 0.035,
    rotationRate: 0.62,
    spinMix: 1,
    colorPhase: 0.38,
    hueCycleRate: 0.1,
    glitchStrength: 0,
    glitchRate: 0,
    sludge: 0.44,
    fieldForm: 1,
    fieldOpacity: 0.62,
    fieldMotion: 0.42,
    cameraZ: 6.7,
    cameraFov: 43,
    cameraDrift: 0.08,
    baseRotX: -0.12,
    baseRotY: -0.2,
    baseRotZ: 0.02,
    idlePitch: 0.014,
    idleYaw: 0.04,
    idleRoll: 0.008,
    keyX: 0.7,
    keyY: 0.2,
    keyZ: 0.72,
    keyIntensity: 1.18,
    fillIntensity: 0.2,
    rimIntensity: 0.66,
    lightSweep: 0.52,
    specular: 0.34,
    glowOpacity: 0.62,
    glowScale: 1.12,
    grainOpacity: 0.2,
    hue: '38deg',
  },
  {
    morph: 0.1,
    cubeOpacity: 1,
    headOpacity: 0,
    modelScale: 1,
    warp: 0.62,
    headWarp: 0,
    chaos: 1,
    shake: 0.14,
    rotationRate: 1.18,
    spinMix: 1,
    colorPhase: 0.7,
    hueCycleRate: 0.3,
    glitchStrength: 1,
    glitchRate: 0.72,
    sludge: 0.8,
    fieldForm: 2,
    fieldOpacity: 0.88,
    fieldMotion: 1,
    cameraZ: 7.7,
    cameraFov: 49,
    cameraDrift: 0.2,
    baseRotX: -0.08,
    baseRotY: 0,
    baseRotZ: 0,
    idlePitch: 0.028,
    idleYaw: 0.08,
    idleRoll: 0.016,
    keyX: -0.9,
    keyY: -0.12,
    keyZ: 0.45,
    keyIntensity: 1.38,
    fillIntensity: 0.11,
    rimIntensity: 1.05,
    lightSweep: 1,
    specular: 0.44,
    glowOpacity: 0.78,
    glowScale: 1.28,
    grainOpacity: 0.28,
    hue: '-42deg',
  },
  {
    morph: 1,
    cubeOpacity: 0,
    headOpacity: 1,
    modelScale: 1.3,
    warp: 0.045,
    headWarp: 0.022,
    chaos: 0.07,
    shake: 0.004,
    rotationRate: 0.035,
    spinMix: 0,
    colorPhase: 0.98,
    hueCycleRate: 0,
    glitchStrength: 0.58,
    glitchRate: 0.16,
    sludge: 0.28,
    fieldForm: 3,
    fieldOpacity: 0.48,
    fieldMotion: 0.12,
    cameraZ: 7.1,
    cameraFov: 36,
    cameraDrift: 0.02,
    baseRotX: 0.01,
    baseRotY: -0.05,
    baseRotZ: -0.01,
    idlePitch: 0.055,
    idleYaw: 0.085,
    idleRoll: 0.04,
    keyX: -0.42,
    keyY: 0.62,
    keyZ: 0.86,
    keyIntensity: 1.34,
    fillIntensity: 0.46,
    rimIntensity: 0.82,
    lightSweep: 0.08,
    specular: 0.7,
    glowOpacity: 0.5,
    glowScale: 1.06,
    grainOpacity: 0.13,
    hue: '74deg',
  },
];

export type ChapterState = (typeof CHAPTERS)[number];

export type AmbientState = { timeScale: number; sceneTime: number };

export type Timeline = ReturnType<typeof gsap.timeline>;

export type HeadMesh = THREE.Mesh<THREE.BufferGeometry, THREE.ShaderMaterial>;

export type Point = { x: number; y: number };

export type TouchOrigin = Point & { pointerId: number };

export type BurnStamp = Point & {
  radius: number;
  rotation: number;
  seed: number;
  createdAt: number;
};

export type SmokeParticle = Point & {
  vx: number;
  vy: number;
  life: number;
  age: number;
  size: number;
};
