version: "3.7"

services:
  wax-attic-splash:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: wax-attic-splash
    volumes:
      - .:/app
    restart: always
    network_mode: host
  wax-attic-splash-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: wax-attic-splash-test
    volumes:
      - .:/app
    network_mode: host
